name: CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
                    # @todo run some tests on 'windows-latest' (needs test env setup scripts for windows to be developed)
                    -   php: '8.4'
                        operating-system: ubuntu-24.04
                    -   php: '8.3'
                        operating-system: ubuntu-22.04
                    -   php: '8.2'
                        operating-system: ubuntu-22.04
                    -   php: '8.1'
                        operating-system: ubuntu-22.04
                    -   php: '8.0'
                        operating-system: ubuntu-22.04
                    -   php: '7.4'
                        operating-system: ubuntu-24.04
                        # nb: the version of phpunit we use does not support code coverage generation on php 8
                        code-coverage: true
                    -   php: '7.3'
                        operating-system: ubuntu-22.04
                    -   php: '7.2'
                        operating-system: ubuntu-22.04
                    -   php: '7.1'
                        operating-system: ubuntu-22.04
                    -   php: '7.0'
                        operating-system: ubuntu-22.04
                    -   php: '5.6'
                        operating-system: ubuntu-22.04
                    -   php: '5.5'
                        operating-system: ubuntu-22.04
                    -   php: '5.4'
                        operating-system: ubuntu-22.04
        steps:
            -    name: checkout code
                 uses: actions/checkout@v3

            -   name: set up env
                # @todo add env setup scripts for windows
                run: |
                  sudo --preserve-env=GITHUB_ACTIONS apt install gettext
                  # locales used by the examples
                  sudo locale-gen de_CH
                  sudo locale-gen en_US
                  sudo locale-gen sr_RS

            -   name: set up php
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: "gettext,mbstring"
                    #ini-values: 'cgi.fix_pathinfo=1, always_populate_raw_post_data=-1'
                    #tools: ${{ matrix.phpunit-version }}
                    coverage: ${{ matrix.code-coverage}}

            # Avoid downloading composer deps on every workflow run. Is this useful for us? Caching the installation of
            # php/apache would be more useful...
            #-
            #    uses: actions/cache@v2
            #    with:
            #        path: /tmp/composer-cache
            #        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            -   name: install dependencies
                run: 'composer install --no-progress'

            -   name: run tests and upload coverage info if needed
                run: |
                    if [ -z "${{ matrix.code-coverage }}" ]; then
                        ./vendor/bin/phpunit -v tests
                    else
                        #./tests/ci/setup/setup_code_coverage.sh enable
                        ./vendor/bin/phpunit -v --coverage-clover=coverage.clover tests
                        if [ -f coverage.clover ]; then
                            wget https://uploader.codecov.io/latest/linux/codecov && \
                            chmod +x codecov && \
                            ./codecov -f coverage.clover
                        else
                            echo "WARNING: code coverage not generated. Is xdebug disabled?"
                        fi
                    fi

                    # now disable the php gettext extension, restart the webserver and run a 2nd set of tests
                    # eg: `phpdismod gettext`
